<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="status" nsURI="https://avatar-project.de/query/status/1.0.0"
    nsPrefix="status">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="copyrightText" value="Copyright (c) 2012 - 2024 Data In Motion and others.&#xA;All rights reserved. &#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;    Data In Motion - initial API and implementation"/>
    <details key="oSGiCompatible" value="true"/>
    <details key="basePackage" value="de.avatar"/>
    <details key="resource" value="XMI"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="QueryRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestId" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumerId" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifier for whoever did the request"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" lowerBound="1" eType="ecore:EClass ../../de.avatar.query.model/model/query.ecore#//Query"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcUri" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryResponse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestId" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//QueryStatusType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryStatusResponse" eSuperTypes="#//QueryResponse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="detailedStatus" eType="#//DetailedQueryStatus"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueryStatusType">
    <eLiterals name="QUERY_COMPLETED"/>
    <eLiterals name="QUERY_ERROR" value="1"/>
    <eLiterals name="QUERY_NO_CONTENT" value="2"/>
    <eLiterals name="TIMEOUT" value="3"/>
    <eLiterals name="QUERY_PENDING" value="4"/>
    <eLiterals name="QUERY_DRYRUN_COMPLETED" value="5"/>
    <eLiterals name="QUERY_CANCELED" value="6"/>
    <eLiterals name="QUERY_INTERRUPTED" value="7"/>
    <eLiterals name="DATA_ANONYMIZED_READY" value="8"/>
    <eLiterals name="PUBLIC_LINK_AVAILABLE" value="9"/>
    <eLiterals name="OPERATION_ERROR" value="10"/>
    <eLiterals name="OTHER" value="100"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailedQueryStatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleConnectorQueryStatus"
        upperBound="-1" eType="#//SingleConnectorQueryStatus" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleConnectorQueryStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorName" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statusResult" eType="#//StatusResult"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" upperBound="-1"
        eType="ecore:EClass ../../de.avatar.metadata.model/model/metadata.ecore#//Metadata"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//QueryStatusType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="ecore:EClass ../../de.avatar.connector.model/model/avatar-connector.ecore#//EndpointResponse"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuccessStatusResult" eSuperTypes="#//StatusResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PendingStatusResult" eSuperTypes="#//StatusResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estRuntime" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorStatusResult" eSuperTypes="#//StatusResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorMessage" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
