services:
    avatar-query:
      #        image: devel.data-in-motion.biz:6000/scj/avatar-query:latest
        image: devel.data-in-motion.biz:6000/scj/avatar-query:latest
        hostname: QBACKEND
        stdin_open: true
        tty: true
        ports:
          - "8089:8089"
        volumes:
          - ./envs/:/opt/avatar/secrets/
        networks:
          - avatar
            #          - nx-avatar-network
    mongodb:
        image: mongo:4.2
        container_name: avatar-mongodb
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017 --quiet
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s
        networks:
           - avatar

networks:
    avatar:
