<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rest" nsURI="http://avatar.de/query/rest/1.0" nsPrefix="rest">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="copyrightText" value="Copyright (c) 2012 - 2024 Data In Motion and others.&#xA;All rights reserved. &#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;    Data In Motion - initial API and implementation"/>
    <details key="rootExtendsInterface" value=""/>
    <details key="basePackage" value="de.avatar"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AvatarRestQuery" abstract="true" interface="true">
    <eAnnotations source="avatar.rest">
      <details key="ContentType" value="application/json"/>
      <details key="Version" value="1.0"/>
    </eAnnotations>
    <eOperations name="getConnetors" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="avatar.rest">
        <details key="Path" value="/connectors"/>
        <details key="Method" value="GET"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getStatus" eType="ecore:EClass ../../de.avatar.query.status.model/model/query-status.ecore#//QueryStatus">
      <eAnnotations source="avatar.rest">
        <details key="Path" value="/status"/>
        <details key="Method" value="GET"/>
      </eAnnotations>
      <eParameters name="id" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="username" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="dryrun" eType="ecore:EClass ../../de.avatar.query.status.model/model/query-status.ecore#//QueryStatus">
      <eAnnotations source="avatar.rest">
        <details key="Path" value="/dryrun"/>
        <details key="Method" value="GET"/>
      </eAnnotations>
      <eParameters name="queryStatus" lowerBound="1" eType="ecore:EClass ../../de.avatar.query.status.model/model/query-status.ecore#//QueryStatus"/>
    </eOperations>
    <eOperations name="run" eType="ecore:EClass ../../de.avatar.query.status.model/model/query-status.ecore#//QueryStatus">
      <eAnnotations source="avatar.rest">
        <details key="Path" value="/run"/>
        <details key="Method" value="GET"/>
      </eAnnotations>
      <eParameters name="queryStatus" lowerBound="1" eType="ecore:EClass ../../de.avatar.query.status.model/model/query-status.ecore#//QueryStatus"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
