@startuml

!theme bluegray
skinparam actorStyle awesome

title Status Request

actor User as U
participant QueryUI as UI
participant RestResource as RR
participant StatusService as RCS
participant StatusWhiteboard as SWB
collections Connectors as Cs
collections DataProviders as DP
participant AvatarGenerator as AG

autonumber
U->UI: send a status request
activate U
UI->RR: send a status request
activate UI 
activate RR
RR->RCS: send a status request
activate RCS
RCS->SWB: triggers status request\nto StatusWhiteboard
activate SWB
SWB->Cs: send status request to pending connectors
activate Cs
Cs->DP: each triggered connector sends status\nrequest to the corresponding data provider
activate DP
DP->Cs: each data provider sends a status\nresponse to the corresponding connector
deactivate DP
Cs->SWB: each triggered connector sends\na status response to the whiteboard
deactivate Cs
note right of SWB
Aggregate responses
end note
SWB->RCS: update status in cache
RCS->RCS: do status update
SWB->AG: sends response result for connectors whose status was successfull 
deactivate SWB
activate AG
AG->AG: aggregate response result
deactivate AG
RCS->RR: send status response 
deactivate RCS
RR->UI: send status response
deactivate RR
UI->U: send status response
deactivate UI
deactivate U

@enduml
