@startuml

!theme bluegray
skinparam actorStyle awesome

title Dry Run

actor User as U
participant QueryUI as UI
participant RestResource as RR
participant RequestWhiteboard as RWB
collections Connectors as Cs
collections DataProviders as DP

autonumber
U->UI: send dry run request
activate U
UI->RR: send dry run request
activate UI
activate RR
RR->RWB: send the dry run request
activate RWB
RWB->Cs: send dry run request to all connectors
activate Cs
Cs->DP: each connector sends the request\nto the corresponding data provider
activate DP
DP->Cs: each data provider sends the response\nto the corresponding connector
deactivate DP
Cs->RWB: each connector sends the\nresponse to the whiteboard
deactivate Cs
note right of RWB
Aggregate responses
end note
RWB->RR: send aggregated dry run response
deactivate RWB
RR->UI: send dry run response
deactivate RR
UI->U: send dry run response
deactivate UI
deactivate U
@enduml
