@startuml

!theme bluegray
skinparam actorStyle awesome

title Download Request

actor User as U
participant QueryUI as UI
participant RestResource as RR
participant AvatarGenerator as AG

autonumber
U->UI: send a download request
activate U
UI->RR: send a download request
activate UI 
activate RR
RR->AG: send a download request
activate AG
AG->RR: send zip archive with aggragted results from all the successfull connectors
deactivate AG
RR->UI: send response
deactivate RR
UI->U: send response
deactivate UI
deactivate U

@enduml

