@startuml
actor QueryUI as UI
actor RestResource as RR
actor RequestWhiteboard as RWB
actor StatusService as RCS
actor StatusWhiteboard as SWB
actor Connectors as Cs
actor AvatarGeneraror as AG

== Send a Dry Run Request: ==

autonumber
UI->RR: send a dry run request
activate UI
activate RR
RR->RWB: send the dry run request
activate RWB
RWB->Cs: send dry run request to all connectors
activate Cs
Cs->RWB: send dry run responses
deactivate Cs
note right of RWB
Aggregate responses
end note
RWB->RR: send aggregated response
deactivate RWB
RR->UI: send dry run response
deactivate RR
deactivate UI

== Send a Complete Request: ==

autonumber
UI->RR: send a query request
activate UI
activate RR
RR->RWB: send a query request
activate RWB
RWB->RCS: cache the request
activate RCS
RCS->RCS: do the cache
deactivate RCS
RWB->Cs: send request to all connectors
activate Cs
Cs->RWB: send status responses
deactivate Cs
note right of RWB
Aggregate responses
end note
RWB->RR: send response (pending status)
deactivate RWB
RR->UI: send response (pending status)
deactivate RR
deactivate UI

== Send a Status Request: ==

autonumber
UI->RR: send a status request
activate UI 
activate RR
RR->RCS: send a status request
activate RCS
RCS->SWB: triggers status request to whiteboard
activate SWB
SWB->Cs: send status request to pending connectors
activate Cs
Cs->SWB: send status response
deactivate Cs
note right of SWB
Aggregate responses
end note
SWB->RCS: update status in cache
RCS->RCS: do status update
SWB->AG: send response for connector that are done
deactivate SWB
activate AG
AG->AG: aggregate response
deactivate AG
RCS->RR: send status response 
deactivate RCS
RR->UI: send status response
deactivate RR
deactivate UI

@enduml